---
- hosts: all
  vars:
   - docroot: /var/www/host.com/public
  tasks:

   - name: Add User 
     become: yes
     user:
        name: app
        comment: "app"
        
   - name: update sudo configuration
     template:
        src: sudoers.j2
        dest: /etc/sudoers
        owner: root
        group: root
        mode: 0o0440
        validate: "visudo -cf %s"
     become: yes

   - name: Clone repo
     become: yes
     git:
        repo: https://github.com/nikoe14/proxydrop.git
        dest: /home/app/proxyapp

   - name: Install python-pip
     become: yes
     apt:
        name: python-pip
        update_cache: yes
  
   - name: install flask with pip
     pip: name=flask
   - name: start flask
     shell: "flask run"
       environment:
         FLASK_APP: /home/app/proxyapp/app.py

   - name: Install Git
     become: yes
     apt:
        name: git
        state: present

   
